services:
  motto:
    build:
      context: .
      args:
        OPEN_AI_API_KEY: ${OPEN_AI_API_KEY}
    image: "ghcr.io/nheek/motto:latest"
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file:
      - .env
    platform: linux/amd64