apiVersion: apps/v1
kind: Deployment
metadata:
  name: motto-deployment
  labels:
    app: motto
spec:
  replicas: 1
  selector:
    matchLabels:
      app: motto
  template:
    metadata:
      labels:
        app: motto
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: motto
        image: nheek/motto:latest
        env:
          - name: OPEN_AI_API_KEY
            valueFrom:
              secretKeyRef:
                name: motto-secret
                key: OPEN_AI_API_KEY
        ports:
        - containerPort: 3000
        resources:
          requests:
            memory: "40Mi"
          limits:
            memory: "100Mi"