name: Build, Push, and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-push-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Image
        run: |
          echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/motto:latest -f Dockerfile .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/motto:latest

      - name: Set up kubectl
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.DO_KUBECONFIG }}" | base64 --decode > $HOME/.kube/config
      
      - name: Create .env file
        run: |
          echo "NEXT_PUBLIC_OPEN_AI_API_KEY"=${{ secrets.NEXT_PUBLIC_OPEN_AI_API_KEY }} > .env

      - name: Create ConfigMap from .env file
        run: |
          kubectl create configmap app-config --from-env-file=.env --dry-run=client -o yaml | kubectl apply -f -

      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl apply -f k8s/ingress.yaml
          kubectl apply -f k8s/hpa.yml
