name: Production - Build, Push, and Deploy Docker Compose

on:
  push:
    branches:
      - main

jobs:
  build-push:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Generate .env file
        run: |
          echo "NODE_ENV=production" >> .env
          echo "OPEN_AI_API_KEY=${{ secrets.OPEN_AI_API_KEY }}" >> .env

      - name: Build and Push Docker Images
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u ${{ secrets.REG_USERNAME }} --password-stdin
          docker compose build
          docker compose push

  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest
    needs: build-push

    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            ssh -q -T -o "StrictHostKeyChecking=no" ${{ secrets.K3S_USERNAME }}@${{ secrets.K3S_IP }} << 'EOF'
            export PATH=$PATH:/usr/local/bin
            kubectl rollout restart deployment -n default motto-d
            curl -d "motto deployed successfully" https://ntfy.nheek.com/${{ secrets.NTFY_TOPIC }}
            EOF